// <auto-generated />
namespace NewsIndy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class replacedplaceboolswithDescriptionproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replacedplaceboolswithDescriptionproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202104061936016_replaced place bools with Description property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
