// <auto-generated />
namespace NewsIndy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fixedvolunteertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedvolunteertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202104051949396_fixed volunteer table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
