// <auto-generated />
namespace NewsIndy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fixedvolunteertable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedvolunteertable2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104051954007_fixed volunteer table2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
